# Generated by Django 4.2 on 2023-05-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThousandVillageSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrepre', models.BinaryField(verbose_name='是否创业')),
                ('survival', models.BinaryField(null=True, verbose_name='是否是生存型创业')),
                ('opp', models.BinaryField(null=True, verbose_name='是否是机会型创业')),
                ('elite', models.BinaryField(verbose_name='是否为精英家庭')),
                ('disinte', models.BinaryField(verbose_name='是否为人力残缺家庭')),
                ('relation', models.DecimalField(decimal_places=5, default=0, max_digits=8, verbose_name='关系文化指数')),
                ('gender', models.BinaryField(verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('marriage', models.BinaryField(verbose_name='婚姻状态')),
                ('religion', models.BinaryField(verbose_name='是否信教')),
                ('faminum', models.IntegerField(verbose_name='家庭成员数量')),
                ('maler', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='家庭男性劳动力占比')),
                ('farmland', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='人均耕地面积')),
                ('income', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='家庭收入水平')),
                ('network', models.IntegerField(verbose_name='个人网络：手机联系人数量')),
                ('mkt', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='当地市场化指数')),
                ('expectation', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='父母期望')),
                ('handicraft', models.BinaryField(verbose_name='是否有一技之长')),
                ('socistatu', models.IntegerField(verbose_name='家庭社会地位')),
                ('hmnCapital', models.IntegerField(verbose_name='受教育时长')),
                ('recptime', models.DateTimeField(null=True, verbose_name='样本调查时间')),
            ],
        ),
    ]
