# Generated by Django 4.2 on 2023-05-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='name',
            field=models.CharField(default='佚名', max_length=20, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='tel',
            field=models.CharField(default=' ', max_length=11, verbose_name='联系电话'),
        ),
    ]
