# Generated by Django 4.2 on 2023-05-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_thousandvillagesurvey_name_thousandvillagesurvey_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='disinte',
            field=models.IntegerField(verbose_name='是否为人力残缺家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='elite',
            field=models.IntegerField(verbose_name='是否为精英家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.IntegerField(verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='gender',
            field=models.IntegerField(verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.IntegerField(verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.IntegerField(verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='opp',
            field=models.IntegerField(null=True, verbose_name='是否是机会型创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.IntegerField(verbose_name='是否信教'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='survival',
            field=models.IntegerField(null=True, verbose_name='是否是生存型创业'),
        ),
    ]
