# Generated by Django 4.2 on 2023-05-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_thousandvillagesurvey_disinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='disinte',
            field=models.BooleanField(verbose_name='是否为人力残缺家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='elite',
            field=models.BooleanField(verbose_name='是否为精英家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.BooleanField(verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='expectation',
            field=models.IntegerField(verbose_name='父母期望:1~4'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='gender',
            field=models.BooleanField(verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.BooleanField(verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.BooleanField(verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='opp',
            field=models.BooleanField(null=True, verbose_name='是否是机会型创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.BooleanField(verbose_name='是否信教'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='socistatu',
            field=models.IntegerField(verbose_name='家庭社会地位:1~6'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='survival',
            field=models.BooleanField(null=True, verbose_name='是否是生存型创业'),
        ),
    ]
