# Generated by Django 4.2 on 2023-05-06 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_thousandvillagesurvey_disinte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='recpplace',
            field=models.CharField(max_length=150, null=True, verbose_name='样本调查地点'),
        ),
    ]
