# Generated by Django 4.2 on 2023-05-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_thousandvillagesurvey_recpplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='remark',
            field=models.CharField(max_length=1500, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='expectation',
            field=models.IntegerField(choices=[(1, '无期望'), (2, '低期望'), (3, '中期望'), (4, '高期望')], verbose_name='父母期望:1~4'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='network',
            field=models.IntegerField(verbose_name='手机联系人数量：'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='socistatu',
            field=models.IntegerField(choices=[(1, '低'), (2, '较低'), (3, '中'), (4, '较高'), (5, '高'), (6, '干部')], verbose_name='家庭社会地位自评:1~6'),
        ),
    ]
