# Generated by Django 4.2 on 2023-05-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_thousandvillagesurvey_remark_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='name',
            field=models.CharField(max_length=20, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='tel',
            field=models.CharField(max_length=11, verbose_name='联系电话'),
        ),
    ]
