# Generated by Django 4.2 on 2023-05-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_thousandvillagesurvey_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='expectation',
            field=models.IntegerField(choices=[(1, '无期望'), (2, '低期望'), (3, '中期望'), (4, '高期望')], verbose_name='父母期望'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='gender',
            field=models.BooleanField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='network',
            field=models.IntegerField(verbose_name='手机联系人数量'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='relation',
            field=models.DecimalField(decimal_places=5, max_digits=8, verbose_name='关系文化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='socistatu',
            field=models.IntegerField(choices=[(1, '低'), (2, '较低'), (3, '中'), (4, '较高'), (5, '高'), (6, '干部')], verbose_name='家庭社会地位自评'),
        ),
    ]
