# Generated by Django 4.2 on 2023-05-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_thousandvillagesurvey_expectation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='farmland',
            field=models.FloatField(max_length=5, verbose_name='人均耕地面积（亩）'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='hmnCapital',
            field=models.IntegerField(verbose_name='受教育时长(年)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='income',
            field=models.FloatField(max_length=5, verbose_name='家庭年收入水平(万元)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='maler',
            field=models.FloatField(max_length=3, verbose_name='家庭男性劳动力占比'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='mkt',
            field=models.FloatField(max_length=4, verbose_name='当地市场化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='relation',
            field=models.FloatField(max_length=5, verbose_name='关系文化指数'),
        ),
    ]
