# Generated by Django 4.2 on 2023-05-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_thousandvillagesurvey_farmland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='farmland',
            field=models.FloatField(max_length=5, verbose_name='人均耕地面积（平方米）'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='income',
            field=models.IntegerField(max_length=5, verbose_name='家庭年收入水平(万元)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='maler',
            field=models.IntegerField(verbose_name='家庭男性劳动力数量'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='mkt',
            field=models.IntegerField(max_length=4, verbose_name='当地市场化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='name',
            field=models.CharField(max_length=33, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='relation',
            field=models.IntegerField(verbose_name='关系文化指数'),
        ),
    ]
