# Generated by Django 4.2 on 2023-05-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_thousandvillagesurvey_farmland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='disinte',
            field=models.BooleanField(default=0, verbose_name='是否为人力残缺家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='elite',
            field=models.BooleanField(default=0, verbose_name='是否为精英家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.BooleanField(default=0, verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='farmland',
            field=models.FloatField(max_length=5, verbose_name='人均耕地面积(平方米)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.BooleanField(default=0, verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.BooleanField(default=0, verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='recpplace',
            field=models.CharField(default='无数据', max_length=150, verbose_name='样本调查地点'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='recptime',
            field=models.DateTimeField(verbose_name='样本调查时间'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.BooleanField(default=0, verbose_name='是否信教'),
        ),
    ]
