# Generated by Django 4.2 on 2023-05-07 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_thousandvillagesurvey_disinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='disinte',
            field=models.BooleanField(verbose_name='是否为人力残缺家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='elite',
            field=models.BooleanField(verbose_name='是否为精英家庭'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.IntegerField(choices=[(0, '未创业'), (1, '创业')], verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.BooleanField(verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='income',
            field=models.IntegerField(verbose_name='家庭年收入水平(万元)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.BooleanField(verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='mkt',
            field=models.IntegerField(verbose_name='当地市场化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.BooleanField(verbose_name='是否信教'),
        ),
    ]
