# Generated by Django 4.2 on 2023-05-07 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_thousandvillagesurvey_disinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.BooleanField(verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='farmland',
            field=models.FloatField(max_length=5, verbose_name='人均耕地面积(亩)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='income',
            field=models.FloatField(max_length=5, verbose_name='家庭年收入水平(万元)'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='mkt',
            field=models.FloatField(max_length=4, verbose_name='当地市场化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='relation',
            field=models.FloatField(max_length=8, verbose_name='关系文化指数'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='socistatu',
            field=models.IntegerField(choices=[(1, '无感'), (2, '低'), (3, '较低'), (4, '中'), (5, '较高'), (6, '高')], verbose_name='家庭社会地位自评'),
        ),
    ]
