# Generated by Django 4.2 on 2023-05-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_thousandvillagesurvey_entrepre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='recptime',
            field=models.DateTimeField(null=True, verbose_name='样本调查时间'),
        ),
    ]
