# Generated by Django 4.2 on 2023-05-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_thousandvillagesurvey_entrepre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='recptime',
            field=models.DateField(verbose_name='样本调查时间'),
        ),
    ]
