# Generated by Django 4.2 on 2023-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_alter_thousandvillagesurvey_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thousandvillagesurvey',
            name='disinte',
        ),
        migrations.RemoveField(
            model_name='thousandvillagesurvey',
            name='elite',
        ),
        migrations.RemoveField(
            model_name='thousandvillagesurvey',
            name='opp',
        ),
        migrations.RemoveField(
            model_name='thousandvillagesurvey',
            name='survival',
        ),
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='entretype',
            field=models.BooleanField(choices=[(0, '生存型创业'), (1, '机会型创业')], null=True, verbose_name='创业原因'),
        ),
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='famtype',
            field=models.IntegerField(choices=[(0, '普通家庭'), (1, '人力残缺家庭'), (2, '精英家庭')], default=0, verbose_name='家庭类型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.IntegerField(verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.BooleanField(choices=[(0, '无特殊技能'), (1, '有除务农外其他技能')], verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.BooleanField(choices=[(0, '未婚'), (1, '已婚')], verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='recpplace',
            field=models.CharField(default='(无数据)', max_length=150, verbose_name='样本调查地点'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.BooleanField(choices=[(0, '无宗教信仰'), (1, '有宗教信仰')], verbose_name='是否信教'),
        ),
    ]
