# Generated by Django 4.2 on 2023-05-07 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_thousandvillagesurvey_disinte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entretype',
            field=models.IntegerField(choices=[(0, '生存型创业'), (1, '机会型创业')], null=True, verbose_name='创业原因'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='gender',
            field=models.IntegerField(choices=[(1, '男'), (0, '女')], verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='handicraft',
            field=models.IntegerField(choices=[(0, '无特殊技能'), (1, '有除务农外其他技能')], verbose_name='是否有一技之长'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='marriage',
            field=models.IntegerField(choices=[(0, '未婚'), (1, '已婚')], verbose_name='婚姻状态'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='religion',
            field=models.IntegerField(choices=[(0, '无宗教信仰'), (1, '有宗教信仰')], verbose_name='是否信教'),
        ),
    ]
