# Generated by Django 4.2 on 2023-05-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_alter_thousandvillagesurvey_entretype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entrepre',
            field=models.IntegerField(choices=[(0, '未创业'), (1, '创业')], verbose_name='是否创业'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entretype',
            field=models.IntegerField(blank=True, choices=[(0, '生存型创业'), (1, '机会型创业')], null=True, verbose_name='创业原因'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='tel',
            field=models.BigIntegerField(verbose_name='联系电话'),
        ),
    ]
