# Generated by Django 4.2 on 2023-05-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_thousandvillagesurvey_entrepre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='tel',
            field=models.CharField(max_length=1000, verbose_name='联系电话'),
        ),
    ]
