# Generated by Django 4.2 on 2023-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_thousandvillagesurvey_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='possibility',
            field=models.FloatField(max_length=4, null=True, verbose_name='创业概率'),
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='entretype',
            field=models.IntegerField(blank=True, choices=[(0, '生存型创业'), (1, '机会型创业'), (2, '其他创业')], null=True, verbose_name='创业原因'),
        ),
    ]
