# Generated by Django 4.2 on 2023-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_thousandvillagesurvey_possibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thousandvillagesurvey',
            name='db',
            field=models.IntegerField(default=1, verbose_name='选择数据集'),
        ),
    ]
