# Generated by Django 4.2 on 2023-06-11 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_thousandvillagesurvey_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('tel_user', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('usertype', models.CharField(max_length=30, verbose_name='用户类型')),
                ('register_time', models.DateTimeField(verbose_name='注册时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
