# Generated by Django 4.2 on 2023-06-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_department_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='tel_user',
            new_name='tel',
        ),
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='tel',
            field=models.CharField(max_length=15, verbose_name='联系电话'),
        ),
        migrations.CreateModel(
            name='EmpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='职员姓名')),
                ('tel', models.CharField(max_length=20, verbose_name='联系电话')),
                ('email', models.CharField(max_length=30, verbose_name='邮箱')),
                ('position', models.CharField(max_length=30, verbose_name='职级')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department')),
            ],
        ),
    ]
