# Generated by Django 4.2 on 2023-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_rename_tel_user_userinfo_tel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thousandvillagesurvey',
            name='remark',
            field=models.CharField(max_length=500, null=True, verbose_name='备注(选填)'),
        ),
    ]
