# Generated by Django 4.2 on 2023-06-13 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_alter_userinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department', to_field='title', verbose_name='所属部门'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.department', to_field='title', verbose_name='部门认证'),
        ),
    ]
