# Generated by Django 4.2 on 2023-06-14 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_alter_empinfo_department_alter_userinfo_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='usertype',
            field=models.IntegerField(choices=[(0, '超级用户'), (1, '普通用户')], verbose_name='用户类型'),
        ),
    ]
