# Generated by Django 4.2 on 2023-06-25 15:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0034_empinfo_password_empinfo_usertype_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='password',
            field=models.CharField(default='e1afb1fe8b9c60274a191396d7781973', max_length=64, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='密码'),
        ),
    ]
