# Generated by Django 4.2 on 2023-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_alter_empinfo_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empinfo',
            name='email',
            field=models.CharField(max_length=30, unique=True, verbose_name='邮箱'),
        ),
    ]
